name: Build FE from workflow call

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        default: ""
        type: string
      s3_host_bucket:
        required: true
        default: ""
        type: string
      chat_id: 
        required: true
        default: ''
        type: string
    secrets:
      token_tele: 
        required: true
      assum_role:
        required: true
# permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
  
jobs:
  DeployAppPro:
    runs-on: macos-latest
    steps: 
      # Stage: Clone repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # test print env
      - name: Test print ENV
        run: echo "Giá trị của: ${{ env.TEST }}"
        # Stage: Install Node.js
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Stage: Build
      - name: Install and Build
        run: |
          npm i --save-dev @types/node
          npm install
          npm update
          npm run build
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.assum_role }}
          role-session-name: GitHubActions-${{ github.ref_name }}-${{ github.run_number }}
          aws-region: ${{ inputs.aws_region }}
      
      - name: Deploy to s3
        run: |
          aws s3 sync www s3://${{ inputs.s3_host_bucket }}/ --quiet
